version: '3.8'

services:
  # Backend API
  radox-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: radox-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MODEL_PATH=/app/data/models/
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: radox-network 